[cadets:cdm18]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

KV_MODE = json

TIME_PREFIX = \"event_time\"\s*:\s*\"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%9NZ
MAX_TIMESTAMP_LOOKAHEAD = 30
TZ = UTC

MAX_DAYS_AGO = 4000
